# Generated by Django 6.0.1 on 2026-02-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech_stack',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Engineer', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
