# Generated by Django 6.0.1 on 2026-02-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_education_project_rename_bio_profile_about_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
