# Generated by Django 6.0.1 on 2026-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_github_profile_linkedin_profile_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(default='Full-time', max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(default='Present', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_projects', models.TextField(blank=True, null=True)),
                ('skills_used', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='year',
        ),
        migrations.AddField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
